language: go

os:
  - linux
  - osx

go:
  - "1.10.x"
  - "1.11.x"

env:
  - GO111MODULE=on

before_install:
  - pip install --user -r tests/pip-req.txt

install:
  - go get -t -v ./...
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/douban/gobeansdb

script:
  - diff <(goimports -d .) <(printf "")
  - make test
