language: go

os:
  - linux
  - osx

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"

env:
  - GO111MODULE=on

before_install:
  - pip install --user -r tests/pip-req.txt

install:
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - diff <(goimports -d .) <(printf "")
  - make install
  - go get -u github.com/douban/gobeansdb
  - make test
