on: [push, pull_request]
name: GoBeansProxy Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        python-version: [2.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Get test tools
      run: go get -u -v golang.org/x/tools/cmd/goimports
    
    - name: Prepare Test
      run: pip install --user -r tests/pip-req.txt
    
    - name: Test
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        diff <(goimports -d .) <(printf "")
        go mod vendor
        go get -u -v github.com/douban/gobeansdb
        make test

    - name: Install
      run: make install
